### ISSUE TITLE
Rozwiązać problem external lateral clearence

### ISSUE THREAD

**Issue by Liptonski** [Shinigami072/Design-Studio-Trafic-Flow-Ninja#10]
Api w polsce podaje ta dane tylko dla 3 drog, więc trzeba w jakiś sposób podawać te dane

**Comment by Liptonski** [comment]
Zaimplementować liczenie ilości zakrętów i na jej podstawie wyliczyć stopień

**Comment by Shinigami072** [comment]
#16
