### ISSUE TITLE
Zwracane wartości są podejżanie wysokie

### ISSUE THREAD

**Issue by wojnicki** [Shinigami072/Design-Studio-Trafic-Flow-Ninja#67]
$ ./tfn.sh --road 3 --length 40 50.069958 19.926751 
Road Query...
WARNING: multiple roads detected
road num: 1  - name: 
road num: 2  - name: 
road num: 3  - name: Aleja Juliusza Słowackiego
Result Query...
road: Aleja Juliusza Słowackiego
speed: 32.0
extra lateral clearance: 1.25
bendiness: 151.0076293554148
width: 11.75
length: 156.8345695298304
intersections: 5
cars per day:  22544690.719403975

Oznaczałoby to 260 pojazdów na sekundę, co nie jest możliwe. 

Bardzo proszę o zweryfikowanie obliczeń.

**Comment by psm8** [comment]
Błędny wynik spowodowany jest niską prędkością średnią na zadanym odcinku. Model nie powinien być używany na zatłoczonych drogach, o czym jest informacja w pliku opis_modelu.pdf, dział wprowadzenie. W szczególności model nie powinien być używany na odcinkach z sygnalizacją świetlną, gdyż czas trwania światła czerwonego i zielonego bezpośrednio wpływa na ruch na danym odcinku, a są to informacje, których model nie bierze pod uwagę i są prawdopodobnie niemożliwe do globalnego pozyskania.

Warto też zauważyć, że długości odcinka 156m jest bardzo niska i parametry drogi uzyskane na tak krótkim odcinku mogą być niereprezentatywne. Informacja o tym jest w opis_modelu.pdf, dział wprowadzenie. Także domyślna wartość tego parametru jest wyższa, aby temu przeciwdziałać.

Aby zapobiec temu w przyszłości:
- dodaliśmy do modelu ostrzeżenie o wartościach spoza zakresu dla których model jest skalibrowany.
- dodaliśmy dział opis danych opis_modelu.pdf, do którego została skopiowana tabela Data Description z wiki.model na gitbhubie oraz kilka słów wyjaśnienia.

Ciężko jest znaleźć lub stworzyć model, który będzie działa dla wszystkich dróg, dlatego zdecydowaliśmy się na modułowość aplikacji i możliwość podmiany modelu czy road providera. Wybrany przez model jest skalibrowany dla pewnego zakresu danych wejściowych i nie próbowaliśmy go sztucznie poprawiać, a zamiast tego daliśmy końcowemu użytkownikowi możliwość jego podmiany na taki bardziej pasujący do jego wymagań. Dane spoza przyjętego przez twórców modelu zakresu mogą dawać błędne wyniki z powodu niezdefiniowanego zachowania poza granicami przedziału. Najlepiej testować model na ulicach bez sygnalizacji świetlnej,czyli najbezpieczniej poza dużymi miastami.

**Comment by wojnicki** [comment]
Dziękuje za szybką reakcje i analizę.
